import React from "react";
import CollectionTemplate from "@/components/ui/CollectionTemplate";
import { getMetadata } from "@/utils/seo";
import type { Metadata } from "next";

export const metadata: Metadata = getMetadata(
  "Exclusive Archive Sale",
  "Shop premium clothing and accessories at a special limited archive discount.",
  "/sale"
);

const PRODUCTS = [
  {
    id: "s1",
    name: "Classic Cashmere Trench Coat",
    price: 499,
    discountPercent: 15,
    rating: 4.8,
    category: "Men",
    brand: "Certitude",
    color: "Beige",
    size: ["M", "L", "XL"],
    description: "Premium double-breasted coat made with pure organic cashmere and structured shoulders for an elegant silhouette.",
    imageSrc: "https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s2",
    name: "Suede Handcrafted Chelsea Boots",
    price: 280,
    discountPercent: 20,
    rating: 4.6,
    category: "Men",
    brand: "Modern Classic",
    color: "Beige",
    size: ["M", "L"],
    description: "Artisan-crafted Italian suede boots with comfortable elastic side panels and durable Goodyear-welted soles.",
    imageSrc: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s3",
    name: "Italian Leather Designer Handbag",
    price: 890,
    discountPercent: 30,
    rating: 5.0,
    category: "Accessories",
    brand: "Atelier",
    color: "Charcoal",
    size: ["M"],
    description: "Iconic structured top-handle bag handcrafted in Milan from scratch-resistant pebbled calfskin.",
    imageSrc: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s4",
    name: "Chronograph Gold Mesh Watch",
    price: 350,
    discountPercent: 10,
    rating: 4.5,
    category: "Accessories",
    brand: "Certitude",
    color: "White",
    size: ["M", "L"],
    description: "Timeless chronograph wristwatch featuring a matte white dial, Swiss movement, and black leather strap.",
    imageSrc: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s5",
    name: "Silk Cocktail Evening Gown",
    price: 650,
    discountPercent: 15,
    rating: 4.9,
    category: "Women",
    brand: "Certitude",
    color: "Blush",
    size: ["S", "M", "L"],
    description: "Exquisite floor-length evening gown crafted from heavy 100% mulberry silk satin with a delicate drape back.",
    imageSrc: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s6",
    name: "Oversized Merino Wool Sweater",
    price: 195,
    discountPercent: 10,
    rating: 4.7,
    category: "Women",
    brand: "EcoKnit",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    description: "Relaxed mock neck sweater chunky knit from responsibly sourced extra-fine Australian merino wool.",
    imageSrc: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s7",
    name: "Kids Cotton Knit Romper Set",
    price: 85,
    discountPercent: 10,
    rating: 4.7,
    category: "Kids",
    brand: "EcoKnit",
    color: "Beige",
    size: ["S", "M"],
    description: "An incredibly soft, organic cotton pointelle knit romper set complete with matching booties.",
    imageSrc: "https://images.unsplash.com/photo-1622290319146-7b63df48a635?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s8",
    name: "Kids Knit Canvas Sneakers",
    price: 65,
    discountPercent: 15,
    rating: 4.4,
    category: "Kids",
    brand: "Modern Classic",
    color: "White",
    size: ["S", "M"],
    description: "Flexible, breathable canvas low-tops featuring convenient hook-and-loop velcro straps.",
    imageSrc: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s9",
    name: "Modern Pilot Gold Sunglasses",
    price: 220,
    discountPercent: 20,
    rating: 4.8,
    category: "Accessories",
    brand: "Modern Classic",
    color: "Cream",
    size: ["M"],
    description: "Luxurious pilot sunglasses with gold-plated metal frames and impact-resistant polarized lenses.",
    imageSrc: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s10",
    name: "Kids Organic Fleece Jacket",
    price: 98,
    discountPercent: 25,
    rating: 4.6,
    category: "Kids",
    brand: "EcoKnit",
    color: "Olive",
    size: ["S", "M", "L"],
    description: "Warm, insulating zip fleece jacket made entirely from recycled post-consumer polyester fibers.",
    imageSrc: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s11",
    name: "Minimalist Linen Utility Shirt",
    price: 120,
    discountPercent: 15,
    rating: 4.5,
    category: "Men",
    brand: "Atelier",
    color: "Cream",
    size: ["S", "M", "L"],
    description: "A breathable, lightweight utility shirt crafted from 100% fine French flax linen, featuring double patch pockets.",
    imageSrc: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "s12",
    name: "Kids Denim Utility Jacket",
    price: 88,
    discountPercent: 40,
    rating: 4.8,
    category: "Kids",
    brand: "Modern Classic",
    color: "Charcoal",
    size: ["S", "M", "L"],
    description: "Classic button-front trucker jacket in durable faded washed cotton denim with authentic hardware.",
    imageSrc: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?q=80&w=400&auto=format&fit=crop",
  },
];

export default function SalePage() {
  return (
    <CollectionTemplate
      title="Sale & Clearance"
      description="Up to 60% Off"
      imageSrc="https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=1200&auto=format&fit=crop"
      initialProducts={PRODUCTS}
    />
  );
}
