import React from "react";
import CollectionTemplate from "@/components/ui/CollectionTemplate";

const PRODUCTS = [
  {
    id: "na1",
    name: "Oversized Merino Wool Sweater",
    price: 195,
    rating: 4.7,
    category: "Women",
    brand: "EcoKnit",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    description: "Relaxed mock neck sweater chunky knit from responsibly sourced extra-fine Australian merino wool.",
    imageSrc: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na2",
    name: "Modern Pilot Gold Sunglasses",
    price: 220,
    discountPercent: 10,
    rating: 4.8,
    category: "Accessories",
    brand: "Modern Classic",
    color: "Cream",
    size: ["M"],
    description: "Luxurious pilot sunglasses with gold-plated metal frames and impact-resistant polarized lenses.",
    imageSrc: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na3",
    name: "Minimalist Linen Utility Shirt",
    price: 120,
    rating: 4.5,
    category: "Men",
    brand: "Atelier",
    color: "Cream",
    size: ["S", "M", "L"],
    description: "A breathable, lightweight utility shirt crafted from 100% fine French flax linen, featuring double patch pockets.",
    imageSrc: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na4",
    name: "Kids Organic Fleece Jacket",
    price: 98,
    rating: 4.6,
    category: "Kids",
    brand: "EcoKnit",
    color: "Olive",
    size: ["S", "M", "L"],
    description: "Warm, insulating zip fleece jacket made entirely from recycled post-consumer polyester fibers.",
    imageSrc: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na5",
    name: "Luxury Silk Square Scarf",
    price: 145,
    rating: 4.9,
    category: "Accessories",
    brand: "Atelier",
    color: "Blush",
    size: ["S", "M"],
    description: "Lustrous 90x90cm twill silk scarf featuring hand-rolled edges and a unique heritage geometric print.",
    imageSrc: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na6",
    name: "Classic Cashmere Trench Coat",
    price: 499,
    discountPercent: 15,
    rating: 4.8,
    category: "Men",
    brand: "Certitude",
    color: "Beige",
    size: ["M", "L", "XL"],
    description: "Premium double-breasted coat made with pure organic cashmere and structured shoulders for an elegant silhouette.",
    imageSrc: "https://images.unsplash.com/photo-1617137968427-85924c800a22?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na7",
    name: "Silk Cocktail Evening Gown",
    price: 650,
    rating: 4.9,
    category: "Women",
    brand: "Certitude",
    color: "Blush",
    size: ["S", "M", "L"],
    description: "Exquisite floor-length evening gown crafted from heavy 100% mulberry silk satin with a delicate drape back.",
    imageSrc: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na8",
    name: "Italian Leather Designer Handbag",
    price: 890,
    rating: 5.0,
    category: "Accessories",
    brand: "Atelier",
    color: "Charcoal",
    size: ["M"],
    description: "Iconic structured top-handle bag handcrafted in Milan from scratch-resistant pebbled calfskin.",
    imageSrc: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na9",
    name: "Suede Handcrafted Chelsea Boots",
    price: 280,
    discountPercent: 20,
    rating: 4.6,
    category: "Men",
    brand: "Modern Classic",
    color: "Beige",
    size: ["M", "L"],
    description: "Artisan-crafted Italian suede boots with comfortable elastic side panels and durable Goodyear-welted soles.",
    imageSrc: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na10",
    name: "Kids Cotton Knit Romper Set",
    price: 85,
    rating: 4.7,
    category: "Kids",
    brand: "EcoKnit",
    color: "Beige",
    size: ["S", "M"],
    description: "An incredibly soft, organic cotton pointelle knit romper set complete with matching booties.",
    imageSrc: "https://images.unsplash.com/photo-1622290319146-7b63df48a635?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na11",
    name: "Chronograph Gold Mesh Watch",
    price: 350,
    discountPercent: 10,
    rating: 4.5,
    category: "Accessories",
    brand: "Certitude",
    color: "White",
    size: ["M", "L"],
    description: "Timeless chronograph wristwatch featuring a matte white dial, Swiss movement, and black leather strap.",
    imageSrc: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "na12",
    name: "Slim Fit Wool Tuxedo Jacket",
    price: 520,
    rating: 4.9,
    category: "Men",
    brand: "Certitude",
    color: "Charcoal",
    size: ["M", "L", "XL", "XXL"],
    description: "Impeccably tailored tuxedo jacket featuring premium Italian virgin wool with elegant satin peak lapels.",
    imageSrc: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=400&auto=format&fit=crop",
  },
];

export default function NewArrivalsPage() {
  return (
    <CollectionTemplate
      title="New Arrivals"
      description="Fresh Styles Just Dropped"
      imageSrc="https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1200&auto=format&fit=crop"
      initialProducts={PRODUCTS}
    />
  );
}
